version=2.0
group=net.anvian.glow_ink_plus
java_version=25

# Common
minecraft_version=26.2
mod_name=Glow Ink Plus Mod
mod_author=anvian
mod_id=glow_ink_plus
license=GPL-3.0
credits=JugadorDeWarzone
description=Add more functions to the glow ink, in this mod you can make the wool and carpets glow.
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

# Fabric
fabric_version=0.152.2+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.6-beta
neoforge_loader_version_range=[4,)

# anvian's lib
anvianslib=1.4.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
