version=1.3
group=net.anvian.glow_ink_plus
java_version=21

# Common
minecraft_version=1.21.3
mod_name=Glow Ink Plus Mod
mod_author=anvian
mod_id=glow_ink_plus
license=GPL-3.0
credits=JugadorDeWarzone
description=Add more functions to the glow ink, in this mod you can make the wool and carpets glow.
minecraft_version_range=[1.21.2, 1.22)
neo_form_version=1.21.3-20241023.131943
parchment_minecraft=1.21.3
parchment_version=2024.12.07

# Fabric
fabric_version=0.114.0+1.21.3
fabric_loader_version=0.16.14

# Forge
forge_version=53.1.0
forge_loader_version_range=[53,)

# NeoForge
neoforge_version=21.3.76
neoforge_loader_version_range=[4,)

# anvian's lib
anvianslib=1.2

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
