package net.anvian.glow_ink_plus.core.item;

import net.anvian.glow_ink_plus.Constants;
import net.anvian.glow_ink_plus.core.block.ModBlocks;
import net.anvian.glow_ink_plus.core.component.ModDataComponents;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.util.Unit;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.anvian.glow_ink_plus.core.item.custom.GlowBedItem;

public class ModItems {
    public static final BlockItem GLOW_WHITE_WOOL = new BlockItem(ModBlocks.GLOW_WHITE_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_WHITE_WOOL_ID)));
    public static final BlockItem GLOW_ORANGE_WOOL = new BlockItem(ModBlocks.GLOW_ORANGE_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_ORANGE_WOOL_ID)));
    public static final BlockItem GLOW_MAGENTA_WOOL = new BlockItem(ModBlocks.GLOW_MAGENTA_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_MAGENTA_WOOL_ID)));
    public static final BlockItem GLOW_LIGHT_BLUE_WOOL = new BlockItem(ModBlocks.GLOW_LIGHT_BLUE_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_BLUE_WOOL_ID)));
    public static final BlockItem GLOW_YELLOW_WOOL = new BlockItem(ModBlocks.GLOW_YELLOW_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_YELLOW_WOOL_ID)));
    public static final BlockItem GLOW_LIME_WOOL = new BlockItem(ModBlocks.GLOW_LIME_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIME_WOOL_ID)));
    public static final BlockItem GLOW_PINK_WOOL = new BlockItem(ModBlocks.GLOW_PINK_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PINK_WOOL_ID)));
    public static final BlockItem GLOW_GRAY_WOOL = new BlockItem(ModBlocks.GLOW_GRAY_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GRAY_WOOL_ID)));
    public static final BlockItem GLOW_LIGHT_GRAY_WOOL = new BlockItem(ModBlocks.GLOW_LIGHT_GRAY_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_GRAY_WOOL_ID)));
    public static final BlockItem GLOW_CYAN_WOOL = new BlockItem(ModBlocks.GLOW_CYAN_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_CYAN_WOOL_ID)));
    public static final BlockItem GLOW_PURPLE_WOOL = new BlockItem(ModBlocks.GLOW_PURPLE_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PURPLE_WOOL_ID)));
    public static final BlockItem GLOW_BLUE_WOOL = new BlockItem(ModBlocks.GLOW_BLUE_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLUE_WOOL_ID)));
    public static final BlockItem GLOW_BROWN_WOOL = new BlockItem(ModBlocks.GLOW_BROWN_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BROWN_WOOL_ID)));
    public static final BlockItem GLOW_GREEN_WOOL = new BlockItem(ModBlocks.GLOW_GREEN_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GREEN_WOOL_ID)));
    public static final BlockItem GLOW_RED_WOOL = new BlockItem(ModBlocks.GLOW_RED_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_RED_WOOL_ID)));
    public static final BlockItem GLOW_BLACK_WOOL = new BlockItem(ModBlocks.GLOW_BLACK_WOOL, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLACK_WOOL_ID)));

    //carpet
    public static final BlockItem GLOW_WHITE_CARPET = new BlockItem(ModBlocks.GLOW_WHITE_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_WHITE_CARPET_ID)));
    public static final BlockItem GLOW_ORANGE_CARPET = new BlockItem(ModBlocks.GLOW_ORANGE_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_ORANGE_CARPET_ID)));
    public static final BlockItem GLOW_MAGENTA_CARPET = new BlockItem(ModBlocks.GLOW_MAGENTA_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_MAGENTA_CARPET_ID)));
    public static final BlockItem GLOW_LIGHT_BLUE_CARPET = new BlockItem(ModBlocks.GLOW_LIGHT_BLUE_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_BLUE_CARPET_ID)));
    public static final BlockItem GLOW_YELLOW_CARPET = new BlockItem(ModBlocks.GLOW_YELLOW_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_YELLOW_CARPET_ID)));
    public static final BlockItem GLOW_LIME_CARPET = new BlockItem(ModBlocks.GLOW_LIME_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIME_CARPET_ID)));
    public static final BlockItem GLOW_PINK_CARPET = new BlockItem(ModBlocks.GLOW_PINK_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PINK_CARPET_ID)));
    public static final BlockItem GLOW_GRAY_CARPET = new BlockItem(ModBlocks.GLOW_GRAY_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GRAY_CARPET_ID)));
    public static final BlockItem GLOW_LIGHT_GRAY_CARPET = new BlockItem(ModBlocks.GLOW_LIGHT_GRAY_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_GRAY_CARPET_ID)));
    public static final BlockItem GLOW_CYAN_CARPET = new BlockItem(ModBlocks.GLOW_CYAN_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_CYAN_CARPET_ID)));
    public static final BlockItem GLOW_PURPLE_CARPET = new BlockItem(ModBlocks.GLOW_PURPLE_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PURPLE_CARPET_ID)));
    public static final BlockItem GLOW_BLUE_CARPET = new BlockItem(ModBlocks.GLOW_BLUE_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLUE_CARPET_ID)));
    public static final BlockItem GLOW_BROWN_CARPET = new BlockItem(ModBlocks.GLOW_BROWN_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BROWN_CARPET_ID)));
    public static final BlockItem GLOW_GREEN_CARPET = new BlockItem(ModBlocks.GLOW_GREEN_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GREEN_CARPET_ID)));
    public static final BlockItem GLOW_RED_CARPET = new BlockItem(ModBlocks.GLOW_RED_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_RED_CARPET_ID)));
    public static final BlockItem GLOW_BLACK_CARPET = new BlockItem(ModBlocks.GLOW_BLACK_CARPET, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLACK_CARPET_ID)));

    //beds
    public static final GlowBedItem GLOW_WHITE_BED = new GlowBedItem(ModBlocks.GLOW_WHITE_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_WHITE_BED_ID)));
    public static final GlowBedItem GLOW_ORANGE_BED = new GlowBedItem(ModBlocks.GLOW_ORANGE_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_ORANGE_BED_ID)));
    public static final GlowBedItem GLOW_MAGENTA_BED = new GlowBedItem(ModBlocks.GLOW_MAGENTA_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_MAGENTA_BED_ID)));
    public static final GlowBedItem GLOW_LIGHT_BLUE_BED = new GlowBedItem(ModBlocks.GLOW_LIGHT_BLUE_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_BLUE_BED_ID)));
    public static final GlowBedItem GLOW_YELLOW_BED = new GlowBedItem(ModBlocks.GLOW_YELLOW_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_YELLOW_BED_ID)));
    public static final GlowBedItem GLOW_LIME_BED = new GlowBedItem(ModBlocks.GLOW_LIME_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIME_BED_ID)));
    public static final GlowBedItem GLOW_PINK_BED = new GlowBedItem(ModBlocks.GLOW_PINK_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PINK_BED_ID)));
    public static final GlowBedItem GLOW_GRAY_BED = new GlowBedItem(ModBlocks.GLOW_GRAY_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GRAY_BED_ID)));
    public static final GlowBedItem GLOW_LIGHT_GRAY_BED = new GlowBedItem(ModBlocks.GLOW_LIGHT_GRAY_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_GRAY_BED_ID)));
    public static final GlowBedItem GLOW_CYAN_BED = new GlowBedItem(ModBlocks.GLOW_CYAN_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_CYAN_BED_ID)));
    public static final GlowBedItem GLOW_PURPLE_BED = new GlowBedItem(ModBlocks.GLOW_PURPLE_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PURPLE_BED_ID)));
    public static final GlowBedItem GLOW_BLUE_BED = new GlowBedItem(ModBlocks.GLOW_BLUE_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLUE_BED_ID)));
    public static final GlowBedItem GLOW_BROWN_BED = new GlowBedItem(ModBlocks.GLOW_BROWN_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BROWN_BED_ID)));
    public static final GlowBedItem GLOW_GREEN_BED = new GlowBedItem(ModBlocks.GLOW_GREEN_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GREEN_BED_ID)));
    public static final GlowBedItem GLOW_RED_BED = new GlowBedItem(ModBlocks.GLOW_RED_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_RED_BED_ID)));
    public static final GlowBedItem GLOW_BLACK_BED = new GlowBedItem(ModBlocks.GLOW_BLACK_BED, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLACK_BED_ID)));

    //stained glass
    public static final BlockItem GLOW_WHITE_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_WHITE_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_WHITE_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_ORANGE_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_ORANGE_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_ORANGE_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_MAGENTA_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_MAGENTA_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_MAGENTA_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_LIGHT_BLUE_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_LIGHT_BLUE_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_BLUE_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_YELLOW_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_YELLOW_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_YELLOW_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_LIME_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_LIME_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIME_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_PINK_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_PINK_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PINK_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_GRAY_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_GRAY_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GRAY_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_LIGHT_GRAY_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_LIGHT_GRAY_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_GRAY_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_CYAN_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_CYAN_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_CYAN_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_PURPLE_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_PURPLE_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PURPLE_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_BLUE_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_BLUE_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLUE_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_BROWN_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_BROWN_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BROWN_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_GREEN_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_GREEN_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GREEN_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_RED_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_RED_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_RED_STAINED_GLASS_ID)));
    public static final BlockItem GLOW_BLACK_STAINED_GLASS = new BlockItem(ModBlocks.GLOW_BLACK_STAINED_GLASS, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLACK_STAINED_GLASS_ID)));

    //candles
    public static final BlockItem GLOW_WHITE_CANDLE = new BlockItem(ModBlocks.GLOW_WHITE_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_WHITE_CANDLE_ID)));
    public static final BlockItem GLOW_ORANGE_CANDLE = new BlockItem(ModBlocks.GLOW_ORANGE_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_ORANGE_CANDLE_ID)));
    public static final BlockItem GLOW_MAGENTA_CANDLE = new BlockItem(ModBlocks.GLOW_MAGENTA_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_MAGENTA_CANDLE_ID)));
    public static final BlockItem GLOW_LIGHT_BLUE_CANDLE = new BlockItem(ModBlocks.GLOW_LIGHT_BLUE_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_BLUE_CANDLE_ID)));
    public static final BlockItem GLOW_YELLOW_CANDLE = new BlockItem(ModBlocks.GLOW_YELLOW_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_YELLOW_CANDLE_ID)));
    public static final BlockItem GLOW_LIME_CANDLE = new BlockItem(ModBlocks.GLOW_LIME_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIME_CANDLE_ID)));
    public static final BlockItem GLOW_PINK_CANDLE = new BlockItem(ModBlocks.GLOW_PINK_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PINK_CANDLE_ID)));
    public static final BlockItem GLOW_GRAY_CANDLE = new BlockItem(ModBlocks.GLOW_GRAY_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GRAY_CANDLE_ID)));
    public static final BlockItem GLOW_LIGHT_GRAY_CANDLE = new BlockItem(ModBlocks.GLOW_LIGHT_GRAY_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_GRAY_CANDLE_ID)));
    public static final BlockItem GLOW_CYAN_CANDLE = new BlockItem(ModBlocks.GLOW_CYAN_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_CYAN_CANDLE_ID)));
    public static final BlockItem GLOW_PURPLE_CANDLE = new BlockItem(ModBlocks.GLOW_PURPLE_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PURPLE_CANDLE_ID)));
    public static final BlockItem GLOW_BLUE_CANDLE = new BlockItem(ModBlocks.GLOW_BLUE_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLUE_CANDLE_ID)));
    public static final BlockItem GLOW_BROWN_CANDLE = new BlockItem(ModBlocks.GLOW_BROWN_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BROWN_CANDLE_ID)));
    public static final BlockItem GLOW_GREEN_CANDLE = new BlockItem(ModBlocks.GLOW_GREEN_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GREEN_CANDLE_ID)));
    public static final BlockItem GLOW_RED_CANDLE = new BlockItem(ModBlocks.GLOW_RED_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_RED_CANDLE_ID)));
    public static final BlockItem GLOW_BLACK_CANDLE = new BlockItem(ModBlocks.GLOW_BLACK_CANDLE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLACK_CANDLE_ID)));

    //stained glass pane
    public static final BlockItem GLOW_WHITE_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_WHITE_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_WHITE_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_ORANGE_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_ORANGE_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_ORANGE_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_MAGENTA_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_MAGENTA_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_MAGENTA_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_LIGHT_BLUE_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_LIGHT_BLUE_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_BLUE_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_YELLOW_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_YELLOW_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_YELLOW_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_LIME_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_LIME_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIME_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_PINK_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_PINK_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PINK_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_GRAY_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_GRAY_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GRAY_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_LIGHT_GRAY_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_LIGHT_GRAY_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_GRAY_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_CYAN_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_CYAN_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_CYAN_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_PURPLE_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_PURPLE_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PURPLE_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_BLUE_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_BLUE_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLUE_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_BROWN_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_BROWN_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BROWN_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_GREEN_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_GREEN_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GREEN_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_RED_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_RED_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_RED_STAINED_GLASS_PANE_ID)));
    public static final BlockItem GLOW_BLACK_STAINED_GLASS_PANE = new BlockItem(ModBlocks.GLOW_BLACK_STAINED_GLASS_PANE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLACK_STAINED_GLASS_PANE_ID)));

    //concrete
    public static final BlockItem GLOW_WHITE_CONCRETE = new BlockItem(ModBlocks.GLOW_WHITE_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_WHITE_CONCRETE_ID)));
    public static final BlockItem GLOW_ORANGE_CONCRETE = new BlockItem(ModBlocks.GLOW_ORANGE_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_ORANGE_CONCRETE_ID)));
    public static final BlockItem GLOW_MAGENTA_CONCRETE = new BlockItem(ModBlocks.GLOW_MAGENTA_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_MAGENTA_CONCRETE_ID)));
    public static final BlockItem GLOW_LIGHT_BLUE_CONCRETE = new BlockItem(ModBlocks.GLOW_LIGHT_BLUE_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_BLUE_CONCRETE_ID)));
    public static final BlockItem GLOW_YELLOW_CONCRETE = new BlockItem(ModBlocks.GLOW_YELLOW_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_YELLOW_CONCRETE_ID)));
    public static final BlockItem GLOW_LIME_CONCRETE = new BlockItem(ModBlocks.GLOW_LIME_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIME_CONCRETE_ID)));
    public static final BlockItem GLOW_PINK_CONCRETE = new BlockItem(ModBlocks.GLOW_PINK_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PINK_CONCRETE_ID)));
    public static final BlockItem GLOW_GRAY_CONCRETE = new BlockItem(ModBlocks.GLOW_GRAY_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GRAY_CONCRETE_ID)));
    public static final BlockItem GLOW_LIGHT_GRAY_CONCRETE = new BlockItem(ModBlocks.GLOW_LIGHT_GRAY_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_GRAY_CONCRETE_ID)));
    public static final BlockItem GLOW_CYAN_CONCRETE = new BlockItem(ModBlocks.GLOW_CYAN_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_CYAN_CONCRETE_ID)));
    public static final BlockItem GLOW_PURPLE_CONCRETE = new BlockItem(ModBlocks.GLOW_PURPLE_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PURPLE_CONCRETE_ID)));
    public static final BlockItem GLOW_BLUE_CONCRETE = new BlockItem(ModBlocks.GLOW_BLUE_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLUE_CONCRETE_ID)));
    public static final BlockItem GLOW_BROWN_CONCRETE = new BlockItem(ModBlocks.GLOW_BROWN_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BROWN_CONCRETE_ID)));
    public static final BlockItem GLOW_GREEN_CONCRETE = new BlockItem(ModBlocks.GLOW_GREEN_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GREEN_CONCRETE_ID)));
    public static final BlockItem GLOW_RED_CONCRETE = new BlockItem(ModBlocks.GLOW_RED_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_RED_CONCRETE_ID)));
    public static final BlockItem GLOW_BLACK_CONCRETE = new BlockItem(ModBlocks.GLOW_BLACK_CONCRETE, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLACK_CONCRETE_ID)));

    //glazed terracotta
    public static final BlockItem GLOW_WHITE_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_WHITE_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_WHITE_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_ORANGE_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_ORANGE_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_ORANGE_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_MAGENTA_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_MAGENTA_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_MAGENTA_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_LIGHT_BLUE_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_LIGHT_BLUE_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_BLUE_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_YELLOW_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_YELLOW_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_YELLOW_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_LIME_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_LIME_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIME_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_PINK_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_PINK_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PINK_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_GRAY_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_GRAY_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GRAY_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_LIGHT_GRAY_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_LIGHT_GRAY_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_GRAY_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_CYAN_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_CYAN_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_CYAN_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_PURPLE_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_PURPLE_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PURPLE_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_BLUE_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_BLUE_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLUE_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_BROWN_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_BROWN_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BROWN_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_GREEN_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_GREEN_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GREEN_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_RED_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_RED_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_RED_GLAZED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_BLACK_GLAZED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_BLACK_GLAZED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLACK_GLAZED_TERRACOTTA_ID)));

    //terracotta
    public static final BlockItem GLOW_WHITE_TERRACOTTA = new BlockItem(ModBlocks.GLOW_WHITE_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_WHITE_TERRACOTTA_ID)));
    public static final BlockItem GLOW_ORANGE_TERRACOTTA = new BlockItem(ModBlocks.GLOW_ORANGE_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_ORANGE_TERRACOTTA_ID)));
    public static final BlockItem GLOW_MAGENTA_TERRACOTTA = new BlockItem(ModBlocks.GLOW_MAGENTA_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_MAGENTA_TERRACOTTA_ID)));
    public static final BlockItem GLOW_LIGHT_BLUE_TERRACOTTA = new BlockItem(ModBlocks.GLOW_LIGHT_BLUE_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_BLUE_TERRACOTTA_ID)));
    public static final BlockItem GLOW_YELLOW_TERRACOTTA = new BlockItem(ModBlocks.GLOW_YELLOW_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_YELLOW_TERRACOTTA_ID)));
    public static final BlockItem GLOW_LIME_TERRACOTTA = new BlockItem(ModBlocks.GLOW_LIME_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIME_TERRACOTTA_ID)));
    public static final BlockItem GLOW_PINK_TERRACOTTA = new BlockItem(ModBlocks.GLOW_PINK_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PINK_TERRACOTTA_ID)));
    public static final BlockItem GLOW_GRAY_TERRACOTTA = new BlockItem(ModBlocks.GLOW_GRAY_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GRAY_TERRACOTTA_ID)));
    public static final BlockItem GLOW_LIGHT_GRAY_TERRACOTTA = new BlockItem(ModBlocks.GLOW_LIGHT_GRAY_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_GRAY_TERRACOTTA_ID)));
    public static final BlockItem GLOW_CYAN_TERRACOTTA = new BlockItem(ModBlocks.GLOW_CYAN_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_CYAN_TERRACOTTA_ID)));
    public static final BlockItem GLOW_PURPLE_TERRACOTTA = new BlockItem(ModBlocks.GLOW_PURPLE_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PURPLE_TERRACOTTA_ID)));
    public static final BlockItem GLOW_BLUE_TERRACOTTA = new BlockItem(ModBlocks.GLOW_BLUE_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLUE_TERRACOTTA_ID)));
    public static final BlockItem GLOW_BROWN_TERRACOTTA = new BlockItem(ModBlocks.GLOW_BROWN_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BROWN_TERRACOTTA_ID)));
    public static final BlockItem GLOW_GREEN_TERRACOTTA = new BlockItem(ModBlocks.GLOW_GREEN_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GREEN_TERRACOTTA_ID)));
    public static final BlockItem GLOW_RED_TERRACOTTA = new BlockItem(ModBlocks.GLOW_RED_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_RED_TERRACOTTA_ID)));
    public static final BlockItem GLOW_BLACK_TERRACOTTA = new BlockItem(ModBlocks.GLOW_BLACK_TERRACOTTA, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLACK_TERRACOTTA_ID)));

    //concrete powder
    public static final BlockItem GLOW_WHITE_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_WHITE_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_WHITE_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_ORANGE_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_ORANGE_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_ORANGE_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_MAGENTA_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_MAGENTA_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_MAGENTA_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_LIGHT_BLUE_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_LIGHT_BLUE_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_BLUE_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_YELLOW_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_YELLOW_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_YELLOW_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_LIME_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_LIME_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIME_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_PINK_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_PINK_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PINK_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_GRAY_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_GRAY_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GRAY_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_LIGHT_GRAY_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_LIGHT_GRAY_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_LIGHT_GRAY_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_CYAN_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_CYAN_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_CYAN_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_PURPLE_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_PURPLE_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_PURPLE_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_BLUE_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_BLUE_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLUE_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_BROWN_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_BROWN_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BROWN_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_GREEN_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_GREEN_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_GREEN_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_RED_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_RED_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_RED_CONCRETE_POWDER_ID)));
    public static final BlockItem GLOW_BLACK_CONCRETE_POWDER = new BlockItem(ModBlocks.GLOW_BLACK_CONCRETE_POWDER, new Item.Properties().useBlockDescriptionPrefix().component(ModDataComponents.GLOWING, Unit.INSTANCE).setId(key(Constants.GLOW_BLACK_CONCRETE_POWDER_ID)));

    private static ResourceKey<Item> key(String name) {
        return ResourceKey.create(Registries.ITEM, Identifier.fromNamespaceAndPath(Constants.MOD_ID, name));
    }
}
