package net.anvian.glow_ink_plus.core.registry;

import net.anvian.glow_ink_plus.Constants;
import net.anvian.glow_ink_plus.core.item.ModItems;
import net.anvian.glow_ink_plus.core.item.custom.GlowBedItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

public class ModItemRegistry {
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(Constants.MOD_ID);

    public static final DeferredItem<BlockItem> GLOW_WHITE_WOOL = ITEMS.register("glow_white_wool", () -> ModItems.GLOW_WHITE_WOOL);
    public static final DeferredItem<BlockItem> GLOW_ORANGE_WOOL = ITEMS.register("glow_orange_wool", () -> ModItems.GLOW_ORANGE_WOOL);
    public static final DeferredItem<BlockItem> GLOW_MAGENTA_WOOL = ITEMS.register("glow_magenta_wool", () -> ModItems.GLOW_MAGENTA_WOOL);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_BLUE_WOOL = ITEMS.register("glow_light_blue_wool", () -> ModItems.GLOW_LIGHT_BLUE_WOOL);
    public static final DeferredItem<BlockItem> GLOW_YELLOW_WOOL = ITEMS.register("glow_yellow_wool", () -> ModItems.GLOW_YELLOW_WOOL);
    public static final DeferredItem<BlockItem> GLOW_LIME_WOOL = ITEMS.register("glow_lime_wool", () -> ModItems.GLOW_LIME_WOOL);
    public static final DeferredItem<BlockItem> GLOW_PINK_WOOL = ITEMS.register("glow_pink_wool", () -> ModItems.GLOW_PINK_WOOL);
    public static final DeferredItem<BlockItem> GLOW_GRAY_WOOL = ITEMS.register("glow_gray_wool", () -> ModItems.GLOW_GRAY_WOOL);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_GRAY_WOOL = ITEMS.register("glow_light_gray_wool", () -> ModItems.GLOW_LIGHT_GRAY_WOOL);
    public static final DeferredItem<BlockItem> GLOW_CYAN_WOOL = ITEMS.register("glow_cyan_wool", () -> ModItems.GLOW_CYAN_WOOL);
    public static final DeferredItem<BlockItem> GLOW_PURPLE_WOOL = ITEMS.register("glow_purple_wool", () -> ModItems.GLOW_PURPLE_WOOL);
    public static final DeferredItem<BlockItem> GLOW_BLUE_WOOL = ITEMS.register("glow_blue_wool", () -> ModItems.GLOW_BLUE_WOOL);
    public static final DeferredItem<BlockItem> GLOW_BROWN_WOOL = ITEMS.register("glow_brown_wool", () -> ModItems.GLOW_BROWN_WOOL);
    public static final DeferredItem<BlockItem> GLOW_GREEN_WOOL = ITEMS.register("glow_green_wool", () -> ModItems.GLOW_GREEN_WOOL);
    public static final DeferredItem<BlockItem> GLOW_RED_WOOL = ITEMS.register("glow_red_wool", () -> ModItems.GLOW_RED_WOOL);
    public static final DeferredItem<BlockItem> GLOW_BLACK_WOOL = ITEMS.register("glow_black_wool", () -> ModItems.GLOW_BLACK_WOOL);

    //carpet
    public static final DeferredItem<BlockItem> GLOW_WHITE_CARPET = ITEMS.register("glow_white_carpet", () -> ModItems.GLOW_WHITE_CARPET);
    public static final DeferredItem<BlockItem> GLOW_ORANGE_CARPET = ITEMS.register("glow_orange_carpet", () -> ModItems.GLOW_ORANGE_CARPET);
    public static final DeferredItem<BlockItem> GLOW_MAGENTA_CARPET = ITEMS.register("glow_magenta_carpet", () -> ModItems.GLOW_MAGENTA_CARPET);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_BLUE_CARPET = ITEMS.register("glow_light_blue_carpet", () -> ModItems.GLOW_LIGHT_BLUE_CARPET);
    public static final DeferredItem<BlockItem> GLOW_YELLOW_CARPET = ITEMS.register("glow_yellow_carpet", () -> ModItems.GLOW_YELLOW_CARPET);
    public static final DeferredItem<BlockItem> GLOW_LIME_CARPET = ITEMS.register("glow_lime_carpet", () -> ModItems.GLOW_LIME_CARPET);
    public static final DeferredItem<BlockItem> GLOW_PINK_CARPET = ITEMS.register("glow_pink_carpet", () -> ModItems.GLOW_PINK_CARPET);
    public static final DeferredItem<BlockItem> GLOW_GRAY_CARPET = ITEMS.register("glow_gray_carpet", () -> ModItems.GLOW_GRAY_CARPET);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_GRAY_CARPET = ITEMS.register("glow_light_gray_carpet", () -> ModItems.GLOW_LIGHT_GRAY_CARPET);
    public static final DeferredItem<BlockItem> GLOW_CYAN_CARPET = ITEMS.register("glow_cyan_carpet", () -> ModItems.GLOW_CYAN_CARPET);
    public static final DeferredItem<BlockItem> GLOW_PURPLE_CARPET = ITEMS.register("glow_purple_carpet", () -> ModItems.GLOW_PURPLE_CARPET);
    public static final DeferredItem<BlockItem> GLOW_BLUE_CARPET = ITEMS.register("glow_blue_carpet", () -> ModItems.GLOW_BLUE_CARPET);
    public static final DeferredItem<BlockItem> GLOW_BROWN_CARPET = ITEMS.register("glow_brown_carpet", () -> ModItems.GLOW_BROWN_CARPET);
    public static final DeferredItem<BlockItem> GLOW_GREEN_CARPET = ITEMS.register("glow_green_carpet", () -> ModItems.GLOW_GREEN_CARPET);
    public static final DeferredItem<BlockItem> GLOW_RED_CARPET = ITEMS.register("glow_red_carpet", () -> ModItems.GLOW_RED_CARPET);
    public static final DeferredItem<BlockItem> GLOW_BLACK_CARPET = ITEMS.register("glow_black_carpet", () -> ModItems.GLOW_BLACK_CARPET);

    //bed
    public static final DeferredItem<GlowBedItem> GLOW_WHITE_BED = ITEMS.register("glow_white_bed", () -> ModItems.GLOW_WHITE_BED);
    public static final DeferredItem<GlowBedItem> GLOW_ORANGE_BED = ITEMS.register("glow_orange_bed", () -> ModItems.GLOW_ORANGE_BED);
    public static final DeferredItem<GlowBedItem> GLOW_MAGENTA_BED = ITEMS.register("glow_magenta_bed", () -> ModItems.GLOW_MAGENTA_BED);
    public static final DeferredItem<GlowBedItem> GLOW_LIGHT_BLUE_BED = ITEMS.register("glow_light_blue_bed", () -> ModItems.GLOW_LIGHT_BLUE_BED);
    public static final DeferredItem<GlowBedItem> GLOW_YELLOW_BED = ITEMS.register("glow_yellow_bed", () -> ModItems.GLOW_YELLOW_BED);
    public static final DeferredItem<GlowBedItem> GLOW_LIME_BED = ITEMS.register("glow_lime_bed", () -> ModItems.GLOW_LIME_BED);
    public static final DeferredItem<GlowBedItem> GLOW_PINK_BED = ITEMS.register("glow_pink_bed", () -> ModItems.GLOW_PINK_BED);
    public static final DeferredItem<GlowBedItem> GLOW_GRAY_BED = ITEMS.register("glow_gray_bed", () -> ModItems.GLOW_GRAY_BED);
    public static final DeferredItem<GlowBedItem> GLOW_LIGHT_GRAY_BED = ITEMS.register("glow_light_gray_bed", () -> ModItems.GLOW_LIGHT_GRAY_BED);
    public static final DeferredItem<GlowBedItem> GLOW_CYAN_BED = ITEMS.register("glow_cyan_bed", () -> ModItems.GLOW_CYAN_BED);
    public static final DeferredItem<GlowBedItem> GLOW_PURPLE_BED = ITEMS.register("glow_purple_bed", () -> ModItems.GLOW_PURPLE_BED);
    public static final DeferredItem<GlowBedItem> GLOW_BLUE_BED = ITEMS.register("glow_blue_bed", () -> ModItems.GLOW_BLUE_BED);
    public static final DeferredItem<GlowBedItem> GLOW_BROWN_BED = ITEMS.register("glow_brown_bed", () -> ModItems.GLOW_BROWN_BED);
    public static final DeferredItem<GlowBedItem> GLOW_GREEN_BED = ITEMS.register("glow_green_bed", () -> ModItems.GLOW_GREEN_BED);
    public static final DeferredItem<GlowBedItem> GLOW_RED_BED = ITEMS.register("glow_red_bed", () -> ModItems.GLOW_RED_BED);
    public static final DeferredItem<GlowBedItem> GLOW_BLACK_BED = ITEMS.register("glow_black_bed", () -> ModItems.GLOW_BLACK_BED);

    //stained glass
    public static final DeferredItem<BlockItem> GLOW_WHITE_STAINED_GLASS = ITEMS.register("glow_white_stained_glass", () -> ModItems.GLOW_WHITE_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_ORANGE_STAINED_GLASS = ITEMS.register("glow_orange_stained_glass", () -> ModItems.GLOW_ORANGE_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_MAGENTA_STAINED_GLASS = ITEMS.register("glow_magenta_stained_glass", () -> ModItems.GLOW_MAGENTA_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_BLUE_STAINED_GLASS = ITEMS.register("glow_light_blue_stained_glass", () -> ModItems.GLOW_LIGHT_BLUE_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_YELLOW_STAINED_GLASS = ITEMS.register("glow_yellow_stained_glass", () -> ModItems.GLOW_YELLOW_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_LIME_STAINED_GLASS = ITEMS.register("glow_lime_stained_glass", () -> ModItems.GLOW_LIME_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_PINK_STAINED_GLASS = ITEMS.register("glow_pink_stained_glass", () -> ModItems.GLOW_PINK_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_GRAY_STAINED_GLASS = ITEMS.register("glow_gray_stained_glass", () -> ModItems.GLOW_GRAY_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_GRAY_STAINED_GLASS = ITEMS.register("glow_light_gray_stained_glass", () -> ModItems.GLOW_LIGHT_GRAY_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_CYAN_STAINED_GLASS = ITEMS.register("glow_cyan_stained_glass", () -> ModItems.GLOW_CYAN_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_PURPLE_STAINED_GLASS = ITEMS.register("glow_purple_stained_glass", () -> ModItems.GLOW_PURPLE_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_BLUE_STAINED_GLASS = ITEMS.register("glow_blue_stained_glass", () -> ModItems.GLOW_BLUE_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_BROWN_STAINED_GLASS = ITEMS.register("glow_brown_stained_glass", () -> ModItems.GLOW_BROWN_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_GREEN_STAINED_GLASS = ITEMS.register("glow_green_stained_glass", () -> ModItems.GLOW_GREEN_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_RED_STAINED_GLASS = ITEMS.register("glow_red_stained_glass", () -> ModItems.GLOW_RED_STAINED_GLASS);
    public static final DeferredItem<BlockItem> GLOW_BLACK_STAINED_GLASS = ITEMS.register("glow_black_stained_glass", () -> ModItems.GLOW_BLACK_STAINED_GLASS);
    //candle
    public static final DeferredItem<BlockItem> GLOW_WHITE_CANDLE = ITEMS.register("glow_white_candle", () -> ModItems.GLOW_WHITE_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_ORANGE_CANDLE = ITEMS.register("glow_orange_candle", () -> ModItems.GLOW_ORANGE_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_MAGENTA_CANDLE = ITEMS.register("glow_magenta_candle", () -> ModItems.GLOW_MAGENTA_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_BLUE_CANDLE = ITEMS.register("glow_light_blue_candle", () -> ModItems.GLOW_LIGHT_BLUE_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_YELLOW_CANDLE = ITEMS.register("glow_yellow_candle", () -> ModItems.GLOW_YELLOW_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_LIME_CANDLE = ITEMS.register("glow_lime_candle", () -> ModItems.GLOW_LIME_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_PINK_CANDLE = ITEMS.register("glow_pink_candle", () -> ModItems.GLOW_PINK_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_GRAY_CANDLE = ITEMS.register("glow_gray_candle", () -> ModItems.GLOW_GRAY_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_GRAY_CANDLE = ITEMS.register("glow_light_gray_candle", () -> ModItems.GLOW_LIGHT_GRAY_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_CYAN_CANDLE = ITEMS.register("glow_cyan_candle", () -> ModItems.GLOW_CYAN_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_PURPLE_CANDLE = ITEMS.register("glow_purple_candle", () -> ModItems.GLOW_PURPLE_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_BLUE_CANDLE = ITEMS.register("glow_blue_candle", () -> ModItems.GLOW_BLUE_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_BROWN_CANDLE = ITEMS.register("glow_brown_candle", () -> ModItems.GLOW_BROWN_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_GREEN_CANDLE = ITEMS.register("glow_green_candle", () -> ModItems.GLOW_GREEN_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_RED_CANDLE = ITEMS.register("glow_red_candle", () -> ModItems.GLOW_RED_CANDLE);
    public static final DeferredItem<BlockItem> GLOW_BLACK_CANDLE = ITEMS.register("glow_black_candle", () -> ModItems.GLOW_BLACK_CANDLE);
    //stained glass pane
    public static final DeferredItem<BlockItem> GLOW_WHITE_STAINED_GLASS_PANE = ITEMS.register("glow_white_stained_glass_pane", () -> ModItems.GLOW_WHITE_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_ORANGE_STAINED_GLASS_PANE = ITEMS.register("glow_orange_stained_glass_pane", () -> ModItems.GLOW_ORANGE_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_MAGENTA_STAINED_GLASS_PANE = ITEMS.register("glow_magenta_stained_glass_pane", () -> ModItems.GLOW_MAGENTA_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_BLUE_STAINED_GLASS_PANE = ITEMS.register("glow_light_blue_stained_glass_pane", () -> ModItems.GLOW_LIGHT_BLUE_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_YELLOW_STAINED_GLASS_PANE = ITEMS.register("glow_yellow_stained_glass_pane", () -> ModItems.GLOW_YELLOW_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_LIME_STAINED_GLASS_PANE = ITEMS.register("glow_lime_stained_glass_pane", () -> ModItems.GLOW_LIME_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_PINK_STAINED_GLASS_PANE = ITEMS.register("glow_pink_stained_glass_pane", () -> ModItems.GLOW_PINK_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_GRAY_STAINED_GLASS_PANE = ITEMS.register("glow_gray_stained_glass_pane", () -> ModItems.GLOW_GRAY_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_GRAY_STAINED_GLASS_PANE = ITEMS.register("glow_light_gray_stained_glass_pane", () -> ModItems.GLOW_LIGHT_GRAY_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_CYAN_STAINED_GLASS_PANE = ITEMS.register("glow_cyan_stained_glass_pane", () -> ModItems.GLOW_CYAN_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_PURPLE_STAINED_GLASS_PANE = ITEMS.register("glow_purple_stained_glass_pane", () -> ModItems.GLOW_PURPLE_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_BLUE_STAINED_GLASS_PANE = ITEMS.register("glow_blue_stained_glass_pane", () -> ModItems.GLOW_BLUE_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_BROWN_STAINED_GLASS_PANE = ITEMS.register("glow_brown_stained_glass_pane", () -> ModItems.GLOW_BROWN_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_GREEN_STAINED_GLASS_PANE = ITEMS.register("glow_green_stained_glass_pane", () -> ModItems.GLOW_GREEN_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_RED_STAINED_GLASS_PANE = ITEMS.register("glow_red_stained_glass_pane", () -> ModItems.GLOW_RED_STAINED_GLASS_PANE);
    public static final DeferredItem<BlockItem> GLOW_BLACK_STAINED_GLASS_PANE = ITEMS.register("glow_black_stained_glass_pane", () -> ModItems.GLOW_BLACK_STAINED_GLASS_PANE);
    //concrete
    public static final DeferredItem<BlockItem> GLOW_WHITE_CONCRETE = ITEMS.register("glow_white_concrete", () -> ModItems.GLOW_WHITE_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_ORANGE_CONCRETE = ITEMS.register("glow_orange_concrete", () -> ModItems.GLOW_ORANGE_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_MAGENTA_CONCRETE = ITEMS.register("glow_magenta_concrete", () -> ModItems.GLOW_MAGENTA_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_BLUE_CONCRETE = ITEMS.register("glow_light_blue_concrete", () -> ModItems.GLOW_LIGHT_BLUE_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_YELLOW_CONCRETE = ITEMS.register("glow_yellow_concrete", () -> ModItems.GLOW_YELLOW_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_LIME_CONCRETE = ITEMS.register("glow_lime_concrete", () -> ModItems.GLOW_LIME_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_PINK_CONCRETE = ITEMS.register("glow_pink_concrete", () -> ModItems.GLOW_PINK_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_GRAY_CONCRETE = ITEMS.register("glow_gray_concrete", () -> ModItems.GLOW_GRAY_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_GRAY_CONCRETE = ITEMS.register("glow_light_gray_concrete", () -> ModItems.GLOW_LIGHT_GRAY_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_CYAN_CONCRETE = ITEMS.register("glow_cyan_concrete", () -> ModItems.GLOW_CYAN_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_PURPLE_CONCRETE = ITEMS.register("glow_purple_concrete", () -> ModItems.GLOW_PURPLE_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_BLUE_CONCRETE = ITEMS.register("glow_blue_concrete", () -> ModItems.GLOW_BLUE_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_BROWN_CONCRETE = ITEMS.register("glow_brown_concrete", () -> ModItems.GLOW_BROWN_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_GREEN_CONCRETE = ITEMS.register("glow_green_concrete", () -> ModItems.GLOW_GREEN_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_RED_CONCRETE = ITEMS.register("glow_red_concrete", () -> ModItems.GLOW_RED_CONCRETE);
    public static final DeferredItem<BlockItem> GLOW_BLACK_CONCRETE = ITEMS.register("glow_black_concrete", () -> ModItems.GLOW_BLACK_CONCRETE);
    //glazed terracotta
    public static final DeferredItem<BlockItem> GLOW_WHITE_GLAZED_TERRACOTTA = ITEMS.register("glow_white_glazed_terracotta", () -> ModItems.GLOW_WHITE_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_ORANGE_GLAZED_TERRACOTTA = ITEMS.register("glow_orange_glazed_terracotta", () -> ModItems.GLOW_ORANGE_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_MAGENTA_GLAZED_TERRACOTTA = ITEMS.register("glow_magenta_glazed_terracotta", () -> ModItems.GLOW_MAGENTA_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_BLUE_GLAZED_TERRACOTTA = ITEMS.register("glow_light_blue_glazed_terracotta", () -> ModItems.GLOW_LIGHT_BLUE_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_YELLOW_GLAZED_TERRACOTTA = ITEMS.register("glow_yellow_glazed_terracotta", () -> ModItems.GLOW_YELLOW_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_LIME_GLAZED_TERRACOTTA = ITEMS.register("glow_lime_glazed_terracotta", () -> ModItems.GLOW_LIME_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_PINK_GLAZED_TERRACOTTA = ITEMS.register("glow_pink_glazed_terracotta", () -> ModItems.GLOW_PINK_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_GRAY_GLAZED_TERRACOTTA = ITEMS.register("glow_gray_glazed_terracotta", () -> ModItems.GLOW_GRAY_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_GRAY_GLAZED_TERRACOTTA = ITEMS.register("glow_light_gray_glazed_terracotta", () -> ModItems.GLOW_LIGHT_GRAY_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_CYAN_GLAZED_TERRACOTTA = ITEMS.register("glow_cyan_glazed_terracotta", () -> ModItems.GLOW_CYAN_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_PURPLE_GLAZED_TERRACOTTA = ITEMS.register("glow_purple_glazed_terracotta", () -> ModItems.GLOW_PURPLE_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_BLUE_GLAZED_TERRACOTTA = ITEMS.register("glow_blue_glazed_terracotta", () -> ModItems.GLOW_BLUE_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_BROWN_GLAZED_TERRACOTTA = ITEMS.register("glow_brown_glazed_terracotta", () -> ModItems.GLOW_BROWN_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_GREEN_GLAZED_TERRACOTTA = ITEMS.register("glow_green_glazed_terracotta", () -> ModItems.GLOW_GREEN_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_RED_GLAZED_TERRACOTTA = ITEMS.register("glow_red_glazed_terracotta", () -> ModItems.GLOW_RED_GLAZED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_BLACK_GLAZED_TERRACOTTA = ITEMS.register("glow_black_glazed_terracotta", () -> ModItems.GLOW_BLACK_GLAZED_TERRACOTTA);
    //terracotta
    public static final DeferredItem<BlockItem> GLOW_WHITE_TERRACOTTA = ITEMS.register("glow_white_terracotta", () -> ModItems.GLOW_WHITE_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_ORANGE_TERRACOTTA = ITEMS.register("glow_orange_terracotta", () -> ModItems.GLOW_ORANGE_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_MAGENTA_TERRACOTTA = ITEMS.register("glow_magenta_terracotta", () -> ModItems.GLOW_MAGENTA_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_BLUE_TERRACOTTA = ITEMS.register("glow_light_blue_terracotta", () -> ModItems.GLOW_LIGHT_BLUE_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_YELLOW_TERRACOTTA = ITEMS.register("glow_yellow_terracotta", () -> ModItems.GLOW_YELLOW_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_LIME_TERRACOTTA = ITEMS.register("glow_lime_terracotta", () -> ModItems.GLOW_LIME_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_PINK_TERRACOTTA = ITEMS.register("glow_pink_terracotta", () -> ModItems.GLOW_PINK_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_GRAY_TERRACOTTA = ITEMS.register("glow_gray_terracotta", () -> ModItems.GLOW_GRAY_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_GRAY_TERRACOTTA = ITEMS.register("glow_light_gray_terracotta", () -> ModItems.GLOW_LIGHT_GRAY_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_CYAN_TERRACOTTA = ITEMS.register("glow_cyan_terracotta", () -> ModItems.GLOW_CYAN_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_PURPLE_TERRACOTTA = ITEMS.register("glow_purple_terracotta", () -> ModItems.GLOW_PURPLE_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_BLUE_TERRACOTTA = ITEMS.register("glow_blue_terracotta", () -> ModItems.GLOW_BLUE_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_BROWN_TERRACOTTA = ITEMS.register("glow_brown_terracotta", () -> ModItems.GLOW_BROWN_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_GREEN_TERRACOTTA = ITEMS.register("glow_green_terracotta", () -> ModItems.GLOW_GREEN_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_RED_TERRACOTTA = ITEMS.register("glow_red_terracotta", () -> ModItems.GLOW_RED_TERRACOTTA);
    public static final DeferredItem<BlockItem> GLOW_BLACK_TERRACOTTA = ITEMS.register("glow_black_terracotta", () -> ModItems.GLOW_BLACK_TERRACOTTA);
    //concrete powder
    public static final DeferredItem<BlockItem> GLOW_WHITE_CONCRETE_POWDER = ITEMS.register("glow_white_concrete_powder", () -> ModItems.GLOW_WHITE_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_ORANGE_CONCRETE_POWDER = ITEMS.register("glow_orange_concrete_powder", () -> ModItems.GLOW_ORANGE_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_MAGENTA_CONCRETE_POWDER = ITEMS.register("glow_magenta_concrete_powder", () -> ModItems.GLOW_MAGENTA_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_BLUE_CONCRETE_POWDER = ITEMS.register("glow_light_blue_concrete_powder", () -> ModItems.GLOW_LIGHT_BLUE_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_YELLOW_CONCRETE_POWDER = ITEMS.register("glow_yellow_concrete_powder", () -> ModItems.GLOW_YELLOW_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_LIME_CONCRETE_POWDER = ITEMS.register("glow_lime_concrete_powder", () -> ModItems.GLOW_LIME_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_PINK_CONCRETE_POWDER = ITEMS.register("glow_pink_concrete_powder", () -> ModItems.GLOW_PINK_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_GRAY_CONCRETE_POWDER = ITEMS.register("glow_gray_concrete_powder", () -> ModItems.GLOW_GRAY_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_LIGHT_GRAY_CONCRETE_POWDER = ITEMS.register("glow_light_gray_concrete_powder", () -> ModItems.GLOW_LIGHT_GRAY_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_CYAN_CONCRETE_POWDER = ITEMS.register("glow_cyan_concrete_powder", () -> ModItems.GLOW_CYAN_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_PURPLE_CONCRETE_POWDER = ITEMS.register("glow_purple_concrete_powder", () -> ModItems.GLOW_PURPLE_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_BLUE_CONCRETE_POWDER = ITEMS.register("glow_blue_concrete_powder", () -> ModItems.GLOW_BLUE_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_BROWN_CONCRETE_POWDER = ITEMS.register("glow_brown_concrete_powder", () -> ModItems.GLOW_BROWN_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_GREEN_CONCRETE_POWDER = ITEMS.register("glow_green_concrete_powder", () -> ModItems.GLOW_GREEN_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_RED_CONCRETE_POWDER = ITEMS.register("glow_red_concrete_powder", () -> ModItems.GLOW_RED_CONCRETE_POWDER);
    public static final DeferredItem<BlockItem> GLOW_BLACK_CONCRETE_POWDER = ITEMS.register("glow_black_concrete_powder", () -> ModItems.GLOW_BLACK_CONCRETE_POWDER);
}
